<h1 style="color:rgb(199, 12, 77);">Bitcoin Price Prediction using Machine Learning</h1>

<h3 style="color:rgb(247, 147, 26)">Notebook Objective</h3>

The purpose of this notebook is to load and explore the Bitcoin historical market dataset, understand its structure, inspect data quality, and perform an initial overview analysis before preprocessing and model development.

 <h3 style="color:rgb(247, 147, 26)">Dataset Description</h3>

This dataset contains historical Bitcoin market data recorded at 1-minute intervals. The dataset includes timestamp information along with Open, High, Low, Close, and Volume values representing Bitcoin trading activity over time.

The dataset will be used for exploratory data analysis, data cleaning, feature engineering, regression modeling, and Bitcoin price prediction.

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [8]:
df = pd.read_csv("../data/raw/btcusd_1-min_data.csv")

In [9]:
df.shape

(7536652, 6)

In [12]:
df.head()

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

      Timestamp  Open  High   Low  Close  Volume
0  1.325412e+09  4.58  4.58  4.58   4.58     0.0
1  1.325412e+09  4.58  4.58  4.58   4.58     0.0
2  1.325412e+09  4.58  4.58  4.58   4.58     0.0
3  1.325412e+09  4.58  4.58  4.58   4.58     0.0
4  1.325412e+09  4.58  4.58  4.58   4.58     0.0

In [14]:
df.tail()

            Timestamp     Open     High      Low    Close    Volume
7536647  1.777680e+09  78250.0  78250.0  78244.0  78245.0  0.233410
7536648  1.777681e+09  78245.0  78254.0  78238.0  78254.0  0.792507
7536649  1.777681e+09  78257.0  78257.0  78250.0  78256.0  0.101332
7536650  1.777681e+09  78254.0  78254.0  78251.0  78251.0  0.208058
7536651  1.777681e+09  78243.0  78244.0  78220.0  78220.0  0.207017

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7536652 entries, 0 to 7536651
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   Timestamp  float64
 1   Open       float64
 2   High       float64
 3   Low        float64
 4   Close      float64
 5   Volume     float64
dtypes: float64(6)
memory usage: 345.0 MB

In [16]:
df.isnull().sum()

Timestamp    0
Open         0
High         0
Low          0
Close        0
Volume       0
dtype: int64

In [17]:
df["Date"] = pd.to_datetime(df["Timestamp"], unit="s")

In [18]:
df.head()

      Timestamp  Open  High   Low  Close  Volume                Date
0  1.325412e+09  4.58  4.58  4.58   4.58     0.0 2012-01-01 10:01:00
1  1.325412e+09  4.58  4.58  4.58   4.58     0.0 2012-01-01 10:02:00
2  1.325412e+09  4.58  4.58  4.58   4.58     0.0 2012-01-01 10:03:00
3  1.325412e+09  4.58  4.58  4.58   4.58     0.0 2012-01-01 10:04:00
4  1.325412e+09  4.58  4.58  4.58   4.58     0.0 2012-01-01 10:05:00

In [19]:
df.tail()

,Timestamp,Open,High,Low,Close,Volume,Date
7536647,1.777680e+09,78250.0,78250.0,78244.0,78245.0,0.233410,2026-05-02 00:08:00
7536648,1.777681e+09,78245.0,78254.0,78238.0,78254.0,0.792507,2026-05-02 00:09:00
7536649,1.777681e+09,78257.0,78257.0,78250.0,78256.0,0.101332,2026-05-02 00:10:00
7536650,1.777681e+09,78254.0,78254.0,78251.0,78251.0,0.208058,2026-05-02 00:11:00
7536651,1.777681e+09,78243.0,78244.0,78220.0,78220.0,0.207017,2026-05-02 00:12:00